@startuml "ProductChangeReceived"
Product->ProductChange : updateOrderBook(OrderBook): (updated) bool
Product->ProductChange : getTrade(msg): Trade
Product->Client: if(updated): onOrderBook(OrderBookView)
Client->ClientListener: notifyOrderBookChanged(clientId, OrderBookView):
ClientListener->ClientServer: sendOrderBookUpdate(orderBookView->serialize())

Product->Client: if(trade) OnTrade(Trade)
Client->ClientListener: notifyOrderBookChanged(clientId, orderBookView->toJSON()):
ClientListener->ClientServer: sendOrderBookUpdate(orderBookView->serialize())

@enduml