ClientTransport->ClientMsgHandler : onMessageReceived(msg)
ClientMsgHandler->ClientFactory: createClient()
Client->OrderBookStorage: subscribe()

MarketMessageHandler->OrderBookStorage: onMarketChange(IMarketChange)
